# Generated by Django 4.1.3 on 2023-01-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='date',
        ),
    ]
